#
# GNU makefile
#

topdir = ../../..

LIB_NAME = libjson-c
INCLUDES = -I$(topdir)/include

SRCS_C = \
    arraylist.c \
    debug.c \
    json_c_version.c \
    json_object.c \
    json_object_iterator.c \
    json_util.c \
    linkhash.c \
    printbuf.c \
    random_seed.c \
    libjson.c

include $(topdir)/build/lib.mk

# DO NOT DELETE THIS LINE -- make depend depends on it.

